CREATE DATABASE IF NOT EXISTS svaap;

USE svaap;

CREATE TABLE IF NOT EXISTS save (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nick VARCHAR(50) NOT NULL,
	level INT NOT NULL,
	score INT NOT NULL,
	primary_weapon VARCHAR(50) NOT NULL,
	secondary_weapon VARCHAR(50));
