package model.level;

import controller.Controller;
import controller.GameController;
import javafx.application.Platform;
import javafx.geometry.Point2D;
import model.Tag;
import model.units.Boss3;
import model.units.Enemy;

import java.util.ArrayList;
import java.util.Arrays;

import static view.GameMain.WINDOW_HEIGHT;
import static view.GameMain.WINDOW_WIDTH;

/**
 * Nelostaso. Säie, joka suorittaa kovakoodatun tason lineaarisesti, ilman looppeja.
 * @author Ilari Anttila
 * @author Jerry Hällfors
 * @author Juha Nuutinen
 * @author Henrik Virrankoski
 */
public class Level4 extends Thread implements Level {

    /**
     * Pelin kontrolleri.
     */
    private Controller controller;

    /**
     * Konstruktori, haetaan kontrolleri-instanssi.
     */
    public Level4() {
        controller = GameController.getInstance();
    }

    @Override
    public void startLevel() {
        start();
    }

    @Override
    public void run() {
        try {
            Thread.sleep(1000);

            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 50));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 150));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 200));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 250));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 300));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 350));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 400));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 450));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 500));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 550));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 600));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 650));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 700));

            Thread.sleep(1_000);

            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 50));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 150));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 200));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 250));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 300));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 350));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 400));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 450));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 500));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 550));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 600));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 650));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 700));

            Thread.sleep(1_000);

            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 50));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 150));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 200));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 250));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 300));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 350));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 400));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 450));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 500));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 550));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 600));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 650));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 700));

            Thread.sleep(1_000);

            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 50));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 150));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 200));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 250));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 300));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 350));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 400));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 450));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 500));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 550));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 600));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 650));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 700));

            Thread.sleep(1_000);

            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 50));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 150));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 200));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 250));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 300));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 350));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 400));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 450));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 500));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 550));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 600));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 650));
            new Enemy(new ArrayList<>(Arrays.asList(Tag.WEAPON_BLASTER_SPRINKLER, Tag.WEAPON_BLASTER, Tag.WEAPON_ROCKET_LAUNCHER, Tag.WEAPON_BLASTER_SHOTGUN, Tag.WEAPON_ROCKET_SHOTGUN, Tag.WEAPON_LASER_GUN)), Enemy.MOVE_SINE, new Point2D(WINDOW_WIDTH+100, 700));

            Thread.sleep(8_000);

            //Viittaa tason viimeiseen pääviholliseen. Käytetään tason loppumisen tarkkailuun.
            Boss3 finalBoss = new Boss3(new Point2D(WINDOW_WIDTH + 100, WINDOW_HEIGHT * 0.5));

            // pyöri silmukas 1 sec välein niin kauan kuin bossi on olemassa
            while(!finalBoss.isDestroyed()){
                Thread.sleep(1_000);
            }

            // Hyperdrive
            controller.changeBackgroundScrollSpeed(2000, 5);
            Thread.sleep(6_000);

            Platform.runLater(() -> controller.addScore(500));

            // Seuraavan tason aloitus
            controller.startLevel(5);

            // Jos ei seuraavaa tasoa, palataan päävalikkoon
            //Platform.runLater(() -> controller.returnToMain());

        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
